ROSTemplateFormatVersion: "2015-09-01"
Description: "OpenShift on AliBaba Cloud Developer Preview"
Parameters:
  # General
  RegionId:
    Type: String
    Default: eu-central-1
  EnvId:
    Type: String
    Default: lab-ay1
  # Networking
  VpcCidrBlock:
    Type: String
    Default: "192.168.0.0/16"
  VpcName:
    Type: String
    Default: ay-cluster-vpc
  VSwitchCidrBlockA:
    Type: String
    Default: "192.168.1.0/24"
  VSwitchCidrBlockB:
    Type: String
    Default: "192.168.2.0/24"
  VSwitchAName:
    Type: String
    Default: ay-vswitch-a
  VSwitchBName:
    Type: String
    Default: ay-vswitch-b
  SecurityGroupName:
    Type: String
    Default: ay-cluster-sg
  ZoneAId:
    Type: String
    Default: eu-central-1a
  ZoneBId:
    Type: String
    Default: eu-central-1b
  # Security
  PublicKeyBody:
    Type: String
  # ECS
  MasterInstanceType:
    Type: String
    Default: ecs.g6.xlarge
  WorkerInstanceType:
    Type: String
    Default: ecs.g6.large
  InstallerSystemDiskSize:
    Type: Number
    Default: 100
  # Imgage Ids on eu-central-1
  # RHEL: m-gw8ei55k4akujv5mqvrv (asks password?)
  # CentOS: centos_7_9_x64_20G_alibase_20240220.vhd (ssh ok)
  # Alibaba Cloud Linux: aliyun_3_9_x64_20G_alibase_20231219.vhd
  LinuxImageId:
    Type: String
    Default: aliyun_3_9_x64_20G_alibase_20231219.vhd
  AllocatePublicIP:
    Type: String
    Default: false
  InternetMaxBandwidthOut:
    Type: Number
    Default: 100
  KeyPairName:
    Type: String
    Default: jufaerma-eu-central-1
  AIImageId:
    Type: String
  InstanceSystemSize:
    Type: Number
    Default: 100
  InstanceSystemLevel:
    Type: String
    Default: L1
  InstanceDataSize:
    Type: Number
    Default: 100
  InstanceDataLevel:
    Type: String
    Default: L1
  DomainName:
    Type: String
    Default: "alicloud-dev.devcluster.openshift.com"
  ClusterName:
    Type: String
    Default: "lab-aliyun-cluster"
Resources:
#             _                      _    
#  _ __   ___| |___      _____  _ __| | __
# | '_ \ / _ \ __\ \ /\ / / _ \| '__| |/ /
# | | | |  __/ |_ \ V  V / (_) | |  |   < 
# |_| |_|\___|\__| \_/\_/ \___/|_|  |_|\_\
  AYVPC:
    Type: "ALIYUN::ECS::VPC"
    Properties:
      CidrBlock:
        Ref: VpcCidrBlock
      RegionId:
        Ref: RegionId
      VpcName:
        Ref: VpcName

  AYVSwitchA:
    Type: "ALIYUN::ECS::VSwitch"
    Properties:
      VpcId:
        Ref: AYVPC
      ZoneId:
        Ref: ZoneAId
      CidrBlock:
        Ref: VSwitchCidrBlockA
      VSwitchName:
        Ref: VSwitchAName

  AYVSwitchB:
    Type: "ALIYUN::ECS::VSwitch"
    Properties:
      VpcId:
        Ref: AYVPC
      ZoneId:
        Ref: ZoneBId
      CidrBlock:
        Ref: VSwitchCidrBlockB
      VSwitchName:
        Ref: VSwitchBName

  AYSecurityGroup:
    Type: "ALIYUN::ECS::SecurityGroup"
    Properties:
      VpcId:
        Ref: AYVPC
      RegionId:
        Ref: RegionId
      SecurityGroupName:
        Ref: SecurityGroupName

  AYSecurityGroupIngressICMP:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: icmp
      PortRange: "-1/-1"
      SourceCidrIp: "0.0.0.0/0"

  # Rules for TCP
  AYSecurityGroupIngressTCP22:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "22/22"
      SourceCidrIp: "0.0.0.0/0"


  AYSecurityGroupIngressTCP1936:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "1936/1936"
      SourceCidrIp: "0.0.0.0/0"


  AYSecurityGroupIngressTCP9000_9999:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "9000/9999"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressTCP10250_10259:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "10250/10259"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressTCP10256:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "10256/10256"
      SourceCidrIp: "0.0.0.0/0"

  # Rules for UDP
  AYSecurityGroupIngressUDP4789:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "4789/4789"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP6081:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "6081/6081"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP9000_9999:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "9000/9999"
      SourceCidrIp: "0.0.0.0/0"
  
  AYSecurityGroupIngressUDP500:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "500/500"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP4500:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      RegionId:
        Ref: RegionId
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "4500/4500"
      SourceCidrIp: "0.0.0.0/0"

  # Rules for TCP/UDP
  AYSecurityGroupIngressTCP30000_32767:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "30000/32767"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressUDP30000_32767:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: udp
      PortRange: "30000/32767"
      SourceCidrIp: "0.0.0.0/0"

  # TODO Those are only needed for control plane
  AYSecurityGroupIngressCPTCP2379_2380:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "2379/2380"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressCPTCP6443:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "6443/6443"
      SourceCidrIp: "0.0.0.0/0"

  AYSecurityGroupIngressCPTCP22:
    Type: "ALIYUN::ECS::SecurityGroupIngress"
    Properties:
      SecurityGroupId:
        Ref: AYSecurityGroup
      IpProtocol: tcp
      PortRange: "22/22"
      SourceCidrIp: "0.0.0.0/0"

  AYNLB:
    Type: "ALIYUN::NLB::LoadBalancer"
    Properties:
      AddressType: "Internet"
      RegionId:
        Ref: RegionId
      VpcId:
        Ref: AYVPC
      LoadBalancerName: ay-cluster-nlb
      ZoneMappings:
        - VSwitchId:
            Ref: AYVSwitchA
          ZoneId:
            Ref: ZoneAId
        - VSwitchId:
            Ref: AYVSwitchB
          ZoneId:
            Ref: ZoneBId

  # LISTENERS
  AYEIPA:
    Type: "ALIYUN::VPC::EIP"
    Properties:
      Bandwidth: "100"
      InternetChargeType: "PayByTraffic"

  AYNatGatewayA:
    Type: "ALIYUN::VPC::NatGateway"
    Properties:
      VpcId: !Ref AYVPC
      VSwitchId: !Ref AYVSwitchA

  AYEIPAAssociation:
    Type: "ALIYUN::VPC::EIPAssociation"
    Properties:
      AllocationId: !Ref AYEIPA
      InstanceId: !Ref AYNatGatewayA

  AYSnatEntry:
    DependsOn: AYEIPAAssociation
    Type: ALIYUN::VPC::SnatEntry
    Properties:
      SourceVSwitchIds:
        - Ref: AYVSwitchA
      SnatIp:
        Fn::GetAtt:
          - AYEIPA
          - EipAddress          
      SnatTableId:
        Fn::GetAtt:
          - AYNatGatewayA
          - SNatTableId

  # ECS Instances
  # AYBastionInstance:
  #  Type: "ALIYUN::ECS::Instance"
  #  Properties:
  #    InstanceName: installer
  #    InstanceType:
  #      Ref: InstallerInstanceType
  #    ImageId:
  #      Ref: LinuxImageId
  #    SecurityGroupId:
  #      Ref: AYSecurityGroup
  #    VSwitchId:
  #      Ref: AYVSwitchA
  #    ZoneId:
  #      Ref: ZoneAId
  #    AllocatePublicIP:
  #      Ref: AllocatePublicIP
  #    InternetMaxBandwidthOut:
  #      Ref: InternetMaxBandwidthOut
  #    KeyPairName:
  #      Ref: KeyPairName
  #    UserData: |
  #      #!/bin/bash
  #      echo "Initializing installer instance"
  #      export AY_LOG=
  #      echo "Initializing installer instance with log" | tee /tmp/ay.log.txt
  #      echo "DISABLED curl -sSL https://raw.githubusercontent.com/faermanj/lab-aliyun/main/ecs-init-installer.sh | bash"

  AYMasterInstance1:
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-master-1
      InstanceType:
        Ref: MasterInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        Ref: ZoneAId
      AllocatePublicIP:
        Ref: AllocatePublicIP
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-master-1
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/master
          Value: ""

  AYMasterInstance2:
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-master-2
      InstanceType:
        Ref: MasterInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        Ref: ZoneAId
      AllocatePublicIP:
        Ref: AllocatePublicIP
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-master-2
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/master
          Value: ""

  AYMasterInstance3:
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-master-3
      InstanceType:
        Ref: MasterInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        Ref: ZoneAId
      AllocatePublicIP:
        Ref: AllocatePublicIP
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-master-3
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/master
          Value: ""

  AYWorkerInstance1:
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-worker-1
      InstanceType:
        Ref: WorkerInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        Ref: ZoneAId
      AllocatePublicIP:
        Ref: AllocatePublicIP
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-worker-1
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/master
          Value: ""

  AYWorkerInstance2:
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-worker-2
      InstanceType:
        Ref: WorkerInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        Ref: ZoneAId
      AllocatePublicIP:
        Ref: AllocatePublicIP
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-worker-2
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/worker
          Value: ""

  AYWorkerInstance3:
    Type: "ALIYUN::ECS::Instance"
    Properties:
      InstanceName:
        Fn::Sub: ${EnvId}-worker-3
      InstanceType:
        Ref: WorkerInstanceType
      ImageId:
        Ref: AIImageId
      SecurityGroupId:
        Ref: AYSecurityGroup
      VSwitchId:
        Ref: AYVSwitchA
      ZoneId:
        Ref: ZoneAId
      AllocatePublicIP:
        Ref: AllocatePublicIP
      InternetMaxBandwidthOut:
        Ref: InternetMaxBandwidthOut
      KeyPairName:
        Ref: KeyPairName
      SystemDiskCategory: cloud_essd
      SystemDiskSize:
        Ref: InstanceSystemSize
      DiskMappings:
        - Category: cloud_essd
          Size:
            Ref: InstanceDataSize
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${EnvId}-worker-3
        - Key: EnvId
          Value:
            Ref: EnvId
        - Key: node-role.kubernetes.io/worker
          Value: ""
   
  AYWorkerServerGroup:
    Type: ALIYUN::NLB::ServerGroup
    Properties:
      ServerGroupName:
        Fn::Sub: ${EnvId}-workers
      VpcId: 
        Ref: AYVPC
      Protocol: TCP
      Servers:
        - ServerType: Ecs
          ServerId:
            Ref: AYWorkerInstance1
          Port: 443
        - ServerType: Ecs
          ServerId:
            Ref: AYWorkerInstance2
          Port: 443
        - ServerType: Ecs
          ServerId:
            Ref: AYWorkerInstance3
          Port: 443

  AYMasterServerGroup:
    Type: ALIYUN::NLB::ServerGroup
    Properties:
      ServerGroupName:
        Fn::Sub: ${EnvId}-masters
      VpcId: 
        Ref: AYVPC
      Protocol: TCP
      Servers:
        - ServerType: Ecs
          ServerId:
            Ref: AYMasterInstance1
          Port: 6443
        - ServerType: Ecs
          ServerId:
            Ref: AYMasterInstance2
          Port: 6443
        - ServerType: Ecs
          ServerId:
            Ref: AYMasterInstance3
          Port: 6443

  NLBListener6443:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 6443
      ServerGroupId: 
        Ref: AYMasterServerGroup

  NLBListener22623:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 22623
      ServerGroupId: 
        Ref: AYMasterServerGroup

  NLBListener80:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 80
      ServerGroupId: 
        Ref: AYWorkerServerGroup
    

  NLBListener443:
    Type: 'ALIYUN::NLB::Listener'
    Properties:
      LoadBalancerId: 
        Ref: AYNLB
      ListenerProtocol: TCP
      ListenerPort: 443
      ServerGroupId: 
        Ref: AYWorkerServerGroup


  AYAPIRecord:
    Type: ALIYUN::DNS::DomainRecord
    Properties:
      DomainName:
        Ref: DomainName
      RR: 
        Fn::Sub: "api.${ClusterName}"
      Type: CNAME
      Value:
        Fn::GetAtt:
          - AYNLB
          - DNSName

  AYAPIINTRecord:
    Type: ALIYUN::DNS::DomainRecord
    Properties:
      DomainName:
        Ref: DomainName
      RR: 
        Fn::Sub: "api-int.${ClusterName}"
      Type: CNAME
      Value:
        Fn::GetAtt:
          - AYNLB
          - DNSName

  AYAPPSRecord:
    Type: ALIYUN::DNS::DomainRecord
    Properties:
      DomainName:
        Ref: DomainName
      RR: 
        Fn::Sub: "*.apps.${ClusterName}"
      Type: CNAME
      Value:
        Fn::GetAtt:
          - AYNLB
          - DNSName

Outputs:
  VPCID:
    Value:
      Ref: AYVPC
  VSwitchAID:
    Value:
      Ref: AYVSwitchA
  VSwitchBID:
    Value:
      Ref: AYVSwitchA
  SecurityGroupID:
    Value:
      Ref: AYSecurityGroup

